### PR TITLE
Adds new "Community" Page

### PR DESCRIPTION
**Pull request by AristurtleDev**
## Description
Adds a new community page that contains links the various social network and community channels for MonoGame.  With the addition of the new page the social link icons were moved from the top navigation to the bottom footer to clean up the top navigation menu as it was getting a bit busy.

## Motivation
This PR was requested to me by @tomspilman 

image

### CODE REVIEW

**Comment by Apostolique** [comment]
In the past there used to be a Gitter / Matrix MonoGame community. Does it still exist? The link used to be <https://gitter.im/MonoGame/MonoGame>. It was somewhat active before 2020.

**Comment by tomspilman** [comment]
> In the past there used to be a Gitter / Matrix MonoGame community

Gitter is dead.  We have the archive of all that content.  Maybe one day we feed it into an AI for archiving.

**Comment by AristurtleDev** [comment]
oh forgot to add link, live preview as always https://mgdocs.aristurtle.net/community/

**Comment by tomspilman** [comment]
@AristurtleDev so a few things:

image

Like i think we should use the same header as we have here in white instead of orange and orange headers:

image

Also the spacing between these feels tight to me....

image

But it feels like that on all the headers IMO, but i'm no expert.

image

**Comment by AristurtleDev** [comment]
@tomspilman 
- margins increased between `<section>` elements and ensured consistent across all pages.  
- The sub headings were adjusted so they are not orange
- I also decreased the size of the social link icons that are in the footer now. They were a bit too big (32px to 24px).

**Review by tomspilman — APPROVED** [review]

**Pull request merged**
