### PR TITLE
Delete articles/getting_started/Images directory

### PR DESCRIPTION
**Pull request by AristurtleDev**
Remove the **I**mages directory so there is no path collision with the **i**mages directory when cloning repository

This resolves issue #15

### CODE REVIEW

**Comment by tomspilman** [comment]
How does this work @AristurtleDev ?  Don't we use these images?

**Comment by AristurtleDev** [comment]
> How does this work @AristurtleDev ? Don't we use these images?

There are two directories in the `/articles/getting_started` directory.  Both are named images however one is capitalized **I** and the other is lowercase **I**.

For unix like file system, this isn't a problem because directories are case sensitive.  For windows (NTFS) file systems, directories are non-case sensitive, so an `Images/` and `images/` directory conflict and both can't exist.

The existing gettings_started documentation was already updated by @harry-cpp to use the lower case directory https://github.com/MonoGame/monogame.github.io/commit/3fe798357349adfd906df6d43c2959d1a3dfc411 however the upper-case directory name was not removed

**Comment by AristurtleDev** [comment]
I realized I might not have answered the question properly @tomspilman 

All images for the getting_started documentation exists both in the `/Images/` and the `/images/` directory.  It's duplicated between the two.  There is no reason to have both directories exists, which leads to the issue of file path collision on NTFS based file systems. By removing the capitalized `/Images/` directory, the documentation pages still load the correct images.

**Review by tomspilman — APPROVED** [review]

**Comment by tomspilman** [comment]
Ok thanks... merging

**Pull request merged**
