### PR TITLE
Adds a Getting Started Article for VSCode

### PR DESCRIPTION
**Pull request by AristurtleDev**
## Description
This PR adds a getting started article for setting up a development environment for to use MonoGame with VSCode. The article contains instructions for Windows, macOS, and Linux, each separated using the tabs feature.

## Live Preview
A live preview of the article can be found at [https://mgdocs.aristurtle.net/articles/getting_started/1_setting_up_your_development_environment_vscode.html](https://mgdocs.aristurtle.net/articles/getting_started/1_setting_up_your_development_environment_vscode.html)

## References
[Issue MonoGame/docs.monogame.github.io#5: feature request: Add Getting started with VS Code article](https://github.com/MonoGame/docs.monogame.github.io/issues/5)

### CODE REVIEW

**Comment by AristurtleDev** [comment]
Marking this as a draft PR for now, but please still review the current documentation written.

Reasons for marking this as a draft PR is that by adding this document, it no longer makes sense to have the macOS / Linux article for getting started.  However, that article, and the Windows article both mention Jetbrains rider.

I would like to propose separating out the Getting Started articles for each IDE (Visual Studio, VSCode, and JetBrains) similar to how [tailwind has their framework guides](https://tailwindcss.com/docs/installation/framework-guides).

**Comment by SimonDarksideJ** [comment]
Can we migrate this PR to the docs repo please @AristurtleDev ?

**Comment by AristurtleDev** [comment]
> Can we migrate this PR to the docs repo please @AristurtleDev ?

@SimonDarksideJ Hey, sorry, this was complete and I marked it as draft due to the question I asked above, which I'll repeat below.

> Reasons for marking this as a draft PR is that by adding this document, it no longer makes sense to have the macOS / Linux article for getting started. However, that article, and the Windows article both mention Jetbrains rider.
> 
> I would like to propose separating out the Getting Started articles for each IDE (Visual Studio, VSCode, and JetBrains) similar to how [tailwind has their framework guides](https://tailwindcss.com/docs/installation/framework-guides).

Otherwise, it's good to go

**Comment by AristurtleDev** [comment]
Closing this, it has been moved to the docs repo at https://github.com/MonoGame/docs.monogame.github.io/pull/18

**Pull request closed without merging**
