### PR TITLE
Updated to use carousel

### PR DESCRIPTION
**Pull request by AristurtleDev**
This updates the home page banner to use a carousel component to display the featured titles.  Each title is set to display for 10 seconds and auto slides to the next image.  The images also cross fade instead of a harsh slide left-out.

### CODE REVIEW

**Comment by tomspilman** [comment]
Could we get a similar drop shadow under the carousel arrows as we have under the center text?

image

**Comment by tomspilman** [comment]
Also we lost the "pixel-art" setting in this change.  It does affect the quality of the result:

image

image

You can see how without it the pixel art gets soft.  My intent with this was to ensure that pixel art looks accurate on the screenshots.

**Comment by AristurtleDev** [comment]
@tomspilman fixed the pixelart setting.  I had it in the script but it was misspelled as `pixelArt` instead of `pixelart`

**Comment by AristurtleDev** [comment]
Also, I've adjusted the left/right chevrons a little.  Playing around with them, doing drop-shadows or outlines, they still had issues on some background like Stardew Valley, they would just be hard to see, for example

image


Instead I created a custom svg chevron that contains a opaque background and is enclosed in a circle.  I've also updated them for the following
-  slightly move them left or right when hovering over them
- Only display on medium (`≥768px`) and higher resolutions. This is so they don't overlay and cramp the text on mobile.  Mobile can still use swipe gesture to swipe between images.


Here is a video of it

https://github.com/MonoGame/monogame.github.io/assets/103014489/f058c0f8-154f-4d35-b89e-7239b0b14584

**Review by tomspilman — APPROVED** [review]

**Pull request merged**
