### PR TITLE
Add filter by tags to showcase

### PR DESCRIPTION
**Pull request by JakeLegendXIII**
Continuing work on #3  
Replicated filter by tag behavior from existing site in javascript.
Code was written in a similar way to the index banner code for consistency.

### CODE REVIEW

**Comment by tomspilman** [comment]
@JakeLegendXIII - if you look in...

https://github.com/MonoGame/monogame.github.io/blob/main/scripts/game-banners.js

That script has a data structure with all the game images and tags.  

It would be best if this feature worked with that structure.  So we can add things once to the structure and it appears on the website.

**Comment by JakeLegendXIII** [comment]
Hey @tomspilman that makes sense. The game-banner currently only has the featured items in the array, so would just require adding the rest. We could add them and have the index pull only the games tagged with Featured for the banner. Then the showcase can be updated to pull all of them from the same array. 

Would you just want to use something like a high level data .js or .json file for this? Assuming that's the direction, but good to ask.

Makes sense to just add the data in one spot and let it dynamically create or show in each place based on the fields.

**Comment by tomspilman** [comment]
> The game-banner currently only has the featured items in the array, so would just require adding the rest. We could add them and have the index pull only the games tagged with Featured for the banner. Then the showcase can be updated to pull all of them from the same array.

Exactly... i had just wrote a ticket for that.

https://github.com/MonoGame/monogame.github.io/issues/17


> Would you just want to use something like a high level data .js or .json file for this? Assuming that's the direction, but good to ask.

That would be fine... either works as long as it is easy to add entries later.

Also keep the existing "pixelart" parameter we have in the existing data table.  It is used to ensure pixel art screen shots get the right filtering when displayed.

> Makes sense to just add the data in one spot and let it dynamically create or show in each place based on the fields.

Exactly.

**Comment by JakeLegendXIII** [comment]
Tackled #17 and the questions around #3 with the latest set of commits.

Let me know if that works! Moved all of the game info to a new game-data.js file. Added a title property to all of them for the mouseover text on showcase. The showcase is now dynamically generated based on the array in the data file.

Filtered the banner list to use just the Featured tag on index.

**Comment by JakeLegendXIII** [comment]
I did add one more thing... Adding the pixelated image-rendering on the small screenshots on showcase as well for pixelart images.

**Comment by tomspilman** [comment]
This looks ok, but want to wait to commit it until tomorrow.  We just have a bunch of traffic right now with the foundation announcement.

**Review by tomspilman — APPROVED** [review]

**Pull request merged**
