### PR TITLE
Convert Site Generator to 11ty

### PR DESCRIPTION
**Pull request by AristurtleDev**
## Description
This Pull Request converts the website to use [11ty](https://www.11ty.dev/) as the static site generator while maintaining DocFX as the generator for the API Reference documentation files.

You can view a live preview of the new site design using this conversion at https://mgdocs.aristurtle.net

## Motivation
DocFX is a wonderful tool for generating an API documentation site for a .NET project.  However, the usefulness of the tool ends there.  It is not designed to be a general purpose static site generator and instead focuses only on it's strength of being a documentation static site generator.

The MonoGame Foundation is currently using DocFX to generate not only the API and supplementary documentation, but also to generate the various pages for the site such as the landing page and about page.  Doing this within DocFX only leads to issues where you either have to design an entire DocFX template from scratch or use CSS bandaids to get around some limitations that are placed in the default and modern templates built into DocFX.

## Purpose
The purpose of this change is to show that the website used for MonoGame can still be done from a static site generator, but one that allows the flexibility of designing a proper website while also incorporating the generated documentation from DocFX.

One of the benefits of this change is that with 11ty, we can use Nunjucks (.njk) templating, which allows for logic to be placed in the template.  DocFX uses Mustache templating, which is logicless.  By providing logic into the templates, this allows the creation of things like the new Blog page that has been added where the foundation can post news and board meeting minutes to instead of just listing links in the About page.

## Future Maintenance
One concern that I know will be placed is the maintainability of the website by making this change.  While a lot of pieces had to be setup manually for this change (e.g. see the **.config** directory), these pieces will require little to no maintenance going forward.  

The actual majority maintenance of the site will still be done through the standard way; by editing the markdown files for the content pages.  When new documentation needs to be added, it's added as markdown files.  There is no additional file format or template language for contributors to learn in order to contribute, it's still just creating and editing markdown files.

> P.S.
> @harry-cpp asked me to open this as a PR instead of an issue for discussion and wanted me to include this note so there is no confusion)

### CODE REVIEW

**Comment by tomspilman** [comment]
> converts the website to use [11ty](https://www.11ty.dev/) as the static site generator

That is fine with me.

Some other notes and my opinions from the new content:

- The MonoGame logo is missing from the header.
- The "History" in the press kit needs a rewrite.  But maybe that can come later?
- Maybe we should link the logo/icon info and not duplicate it to the presskit.
- I'm not a big fan of a Blog as it usually goes stale, but if everyone else wants it that is fine.

The stuff on the Donation page is getting way too big IMO:

image

- The patreon button and the patreon data could be half the size they are.
- The old donations wall could also be smaller to shorten the list.
- The text for the old donations wall should make it clear these are old donations.

**Comment by AristurtleDev** [comment]
> * The MonoGame logo is missing from the header.

This is an odd issue, and it may be from my web hosting setup on my server causing it, but the logo should appear in the header, or at least it's defined in the to show it in the header.  I don't host through gh-pages, the demo site is run from my own server. 

image


> The "History" in the press kit needs a rewrite. But maybe that can come later?  

This section I took from the original About page in the old site (https://www.monogame.rocks/about/) and added the snippet at the end about the Foundation being formed.  Updating it is straight forward, just need to know what text to put there. 


> Maybe we should link the logo/icon info and not duplicate it to the presskit.  

Would you just want the Logos & Icons section to inform them to visit the branding GitHub repo (https://github.com/MonoGame/MonoGame.Logo) for that information?  If so, would you want to remove the .zip download link from the presskit page directly or keep it along with the link to the branding repo?


> I'm not a big fan of a Blog as it usually goes stale, but if everyone else wants it that is fine.

The idea behind the blog page is to more so be an official place to post news and updates about MonoGame and/or the Foundation.  Things like the board meeting notes, official releases/updates, etc.  Not necessarily a blog in the traditional since that is updated frequently.  I guess more of a "News" page than a blog? Could be renamed.  

> The stuff on the Donation page is getting way too big IMO:
> 
> -  The patreon button and the patreon data could be half the size they are.
> 
> -  The old donations wall could also be smaller to shorten the list.
> 
> -  The text for the old donations wall should make it clear these are old donations.

This is good feedback, I'll restructure this page based on this.

**Comment by tomspilman** [comment]
> Would you just want the Logos & Icons section to inform them to visit the branding GitHub repo

Yes i think so.

> would you want to remove the .zip download link from the presskit page directly

It seems ok to keep it linked.

Links are generally fine... just dislike duplicated information that we later have to update in multiple places.  It just makes maintenance harder.


A few more things i noticed:

- Remove the "Based in Texas, USA" on the presskit.  It is just a technicality it is and not like a "feature".
- The "The MonoGame Foundation" link is broken on the press kit.

**Comment by SimonDarksideJ** [comment]
Gotta say, I love it.  But another task (related to this) is we need more updated content for the presskit.

**Comment by AristurtleDev** [comment]
@tomspilman I've made the following changes

- Presskit page
    - Removed the "Based in Texas" statement
    - Fixed the foundation link (was absolute but was broken because the site isn't using this version yet, so made it made relative)
    - Refer visitors to the Branding and Logos repository for logos and branding guidelines
        - Download as .zip link kept on presskit page.  This .zip link is the link to the .zip in the Github Repo's release page
    - Foundation members are pulled from `foundation.json` data instead of hard coded in page.

- Donate Page
    -  Header was adjusted to be a 2-split column with patreon states on the right.  Added a visual count up when page is loaded for stats
    - Donation section text was updated to state "... is a preserved list..." to imply it's an immutable list of previous donations
    - Border and padding removed from each donor, bottom margin adjusted, creating a ~37% reduction in length of page (8131px down to 5083px total page height).

While working on this, I was talking in the discord, and one suggestion was to move the old donation list to it's own page that can be linked to from within the Donate page.  It's not a terrible suggestion, if this is something you think would be better I can do that and move it to it's own page for preservation.

Also to the header logo not appearing that you mentioned initially, I noticed this while checking the site from my phone. From what I can tell, it appears to be a caching issue, which could be caused because of my web server as I mentioned before.  I'm going to switch this to gh-pages hosted just like the actual MG site later to see if that is what's causing it.

**Comment by AristurtleDev** [comment]
> Gotta say, I love it. But another task (related to this) is we need more updated content for the presskit.

@SimonDarksideJ If there is any relevant information or images that can be put on the presskit page, send em my way and I can add them.

The information on the page as it is designed now is just the information I had available from the original MonoGame site and the videos from the YouTube channel.  

You should also be able to submit a PR in my branch if there's information you can think to add if you or anyone else would rather do that.

**Comment by SimonDarksideJ** [comment]
It shouldn't affect this upgrade @AristurtleDev , just notes that the foundation needs to review publishable content for 2024.

**Comment by tomspilman** [comment]
@AristurtleDev Do you happen to have a 4K display on your system?  

I wonder because for me on a 2K display it always feels like your designs feel huge on my system:

**Comment by AristurtleDev** [comment]
@tomspilman No, it's mostly on a MacBook, but now that you pointed it out I just noticed that for some reason my browser was on 80% zoom. This is completely my fault.

Even with that said, the text underneath each heading was using the [`lead`](https://getbootstrap.com/docs/5.3/content/typography/#lead) class from bootstrap as a stylistic choice. but yea, now that I reset the browser zoom, it's too big.  That's on me.

**Comment by tomspilman** [comment]
> but now that you pointed it out I just noticed that for some reason my browser was on 80% zoom on my Macbook. 

Ahh... i knew something was up.  It just always felt oversized to me... makes perfect sense why.

Let me know once your test site is updated with the changes.

**Comment by AristurtleDev** [comment]
@tomspilman new preview is up with the following changes

- Style chnages
    - `lead` class removed from `<p>` tags to reduce paragraph text size
    - `text-uppercase` class removed from headers. This was a stylistic choice originally because of using `lead` with paragraphs
    - Ensure constant header styling (orange with in-page link) across main pages.  Was missing style on a couple of them
    - Patreon stats font adjusted smaller
    - Patreon button adjusted to remove extra padding and reduce element and font size
    - Changed cross-platform-logos icons to use `grid` instead of `flex-box` for a more even layout
    - Reduced size of cross-platform-logo icons
    - Made cross-platform list utilize a 2-column layout on mobile to decrease overall page height/scrolling
    - Reduces element size of the Open Source section on the home page by switching the 3-column layout to use the `mg-card` element setup
    - Made footer section lists utilize a 2-column layout on mobile to decrease overall page height/scrolling.

- Bug fixes
    - Documentation base template updates so that pages like bylaws and presskit that hide the left hand side table of contents section utilize the full page width instead of leaving an empty left column.

- New changes
    - Background Images used in the `mg-card` elements now have a `transform: scale(1.1);` property on hover.  A `prefers-reduced-motion` media query was added to remove the scale effect for users that use the reduce motion accessibility option in the operating system.  This affects the images on cards used on the blog and the showcase pages.

**Review by tomspilman — APPROVED** [review]

**Comment by tomspilman** [comment]
Looks better now... less huge stuff.

There are other fixes to do, but the change to the new site generator is the main thing in this PR.

Will talk to the board tomorrow morning and will likely merge this after.

**Comment by AristurtleDev** [comment]
@tomspilman sounds good.  If there are any questions on the generator specifically (11ty) feel free to ping me and I can try and answer anything. 

Another things I'd liked to mention is that for the blog page, the images uses for the blogs are all the same, just placeholder images I created real quick to use. Feel free to change these to something more official

**Pull request merged**
