### PR TITLE
Showcase logo cleanup

### PR DESCRIPTION
**Pull request by tomspilman**
I removed the drop shadows from the showcase logo images and added CSS to create a consistent drop shadow on all the logos.

I also edited the showcase issue template to correct issues we've had with submissions.

### CODE REVIEW

**Comment by tomspilman** [comment]
@AristurtleDev what do you think of this change?

We had a mix of logos with and without shadows of different kinds.  Instead the CSS shadow is consistent and makes things simpler for submissions i think.

**Comment by AristurtleDev** [comment]
@tomspilman I think this is a good change to allow the shadow to be consistent across all logos.  One thing I noticed though is the shadow has a `6px` radius for the Gaussian blur, and is `#222` which is slightly gray-ish making the drop shadow lighter.  It makes some of the logos, especially those that are over darker backgrounds look washed out I think.  

I took some screenshot comparisons for you of different logos.  For each comparison, the first logo is the original way it appears, the second logo is with your change, and the third logo is adjusting the Gaussian blur radius to `1px` and setting the color to `rgba(0,0,0,1)`

image
image
image
image
image
image
image
image
image

For some of these, like Streets of Rage and Ty, the `6px` Gaussian blur radius and `#222` color make the drop shadow hardly even noticeable, but they pop with the `1px` `rgba(0,0,0,1)` change.  Others, like Barotrauma don't wash out the drop shadow and still allow it to pop on a dark background.  Others, like Daryl and Infinite Flight, the change is super noticeable.

This is just a though after looking over the change.

**Comment by tomspilman** [comment]
Hey @AristurtleDev 

My intent was to avoid having a hard black shadow.  I don't feel it looks good.

I was looking for a slight darkening behind the logo to make it stand out from the background.  

Do you have some recommendations based on that?

**Comment by AristurtleDev** [comment]
@tomspilman what if instead of a shadow, we did a classic outline with

```css
#credits-logo {
    filter: drop-shadow(1px 1px 1px rgba(0, 0, 0, 1)) 
            drop-shadow(-1px -1px 1px rgba(0, 0, 0, 1))
            drop-shadow(1px -1px 1px rgba(0, 0, 0, 1)) 
            drop-shadow(-1px 1px 1px rgba(0, 0, 0, 1))
}
```

Not sure if this falls into the same category of a hard shadow to you or not since it's an outline and not a shadow.

image

**Comment by tomspilman** [comment]
> what if instead of a shadow, we did a classic outline with

@AristurtleDev no i wanted to avoid that as it is almost an altering the game logo. 

I'm happy with the drop shadow being a subtle drop shadow.  But i will increase its size a bit and look for a simple fix for the Barotrauma case.

**Pull request merged**
